com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : -26: Package com.github.android.removeduplicates new target SDK 22 doesn't support runtime permissions but the old target SDK 25 does.